name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Elixir and Erlang/OTP
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16'
        otp-version: '26.1'

    # Fetch project dependencies
    - name: Install dependencies
      run: mix deps.get

    # Compile the project and fail on warnings
    - name: Compile
      run: mix compile --warnings-as-errors

    # Run the test suite with coverage enabled
    - name: Run tests with coverage
      run: mix test --cover

    # Generate an HTML coverage report
    - name: Generate coverage HTML
      run: mix coveralls.html
      env:
        MIX_ENV: test

    # Upload the HTML coverage report as an artifact
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: cover/
